default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    sh("flutter build apk --debug")
    gradle(
      task: "bundle", 
      build_type: "Release",
    )
    supply(
      track:'internal',
      skip_upload_changelogs: true,
      skip_upload_apk: true,
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end
end
